name: imgur
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  go_router: ^14.2.7
  dio: ^5.7.0
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  logging: ^1.2.0
  loading_animation_widget: ^1.2.1
  http: ^1.2.2

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  mocktail: ^1.0.4
  build_runner: ^2.4.12

flutter:

  uses-material-design: true
